version: '2.1'
services:
  cassandra:
    container_name: game-db
    image: cassandra
    ports:
      - "9042:9042"
    volumes:
      - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
  discovery-service:
    container_name: discovery-service
    build: ../discovery-service
    ports:
    - "8761:8761"
    networks:
      - defaultNetwork
  gateway-service:
    container_name: gateway-service
    build: ../gateway-service
    ports:
    - "8662:8662"
    links:
      - "discovery-service:discoveryService"
    depends_on:
      - discovery-service
    networks:
      - defaultNetwork
networks:
  defaultNetwork:
