version: '3.3'

services:
  postgres:
    restart: "no"
    container_name: gss_postgres
    image: postgres:alpine
    ports:
      - "1234:5432"
    volumes:
      - gss_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gss
      POSTGRES_PASSWORD: P10tr3k
      POSTGRES_DB: gss
    networks:
      - gss_default
volumes:
  gss_data:
    external: true

networks:
  gss_default:
    driver: bridge
